version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskboard
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend-java
    container_name: backend-java
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskboard
      SPRING_DATASOURCE_USERNAME: devops
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"

  gateway:
    build: ./gateway-node
    container_name: gateway-node
    depends_on:
      - backend
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend-react
    container_name: frontend-react
    depends_on:
      - gateway
    ports:
      - "5173:80"

volumes:
  db_data:
