global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'springboot'
    static_configs:
      - targets: ['backend-java:8080']

  - job_name: 'express'
    static_configs:
      - targets: ['gateway-node:3000']
